name = "fitbit-health-tracker"
main = "src/index.ts"
compatibility_date = "2026-01-26"

d1_databases = [
  { binding = "FITBIT_DB", database_name = "fitbit_health", database_id = "a4762736-497d-4bc9-96c0-b22cf25ecf36" }
]

[triggers]
crons = ["15 1 * * *", "*/2 * * * *"]

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
DEBUG_SLEEP = "1"
