name = "fitbit-health-tracker"
main = "src/index.ts"
compatibility_date = "2026-01-26"

kv_namespaces = [
  { binding = "FITBIT_KV", id = "11196e8b1df14397914bdb09d9123bde", preview_id = "0076001f08cb4fd091ef41d559e67289" }
]

d1_databases = [
  { binding = "FITBIT_DB", database_name = "fitbit_health", database_id = "a4762736-497d-4bc9-96c0-b22cf25ecf36" }
]

[triggers]
crons = ["15 1 * * *"]

